### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by nerpianicolindo** [gentritabazi01/Larapi#30]
I'm trying to make and api service based in  [gentritabazi01/Clean-Laravel-Api][1] and larapi. I can't solve the problem with CORS when i make request from different servers to my api . The related is the following: 

> Access to XMLHttpRequest at 'https://dev.......com/users' from origin 'http://segu........com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Since 2 days i was reading documentation from CORS and Laravel and any solution solve my problem. I tried creating a middleware and add the necessary headers:

    //Infrastructure\Http\Middlewares\Cors
        <?php
        use Closure;
        class Cors
        {
          public function handle($request, Closure $next)
          {
            return $next($request)
               //Url a la que se le dará acceso en las peticiones
              ->header("Access-Control-Allow-Origin", "*")
              //Métodos que a los que se da acceso
              ->header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE")
              //Headers de la petición
              ->header("Access-Control-Allow-Headers", "*"); 
          }
        }

I tried to using the package [Fruitcake][2] from  laravel, like is used on base proyect.

    //Infrastructur/Http/Kernel.php
        class Kernel extends HttpKernel
        {
            /**
             * The application's global HTTP middleware stack.
             *
             * These middleware are run during every request to your application.
             *
             * @var array
             */
            protected $middleware = [
                \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
                \Infrastructure\Http\Middlewares\EncryptCookies::class,
                \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
                \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
                \Fruitcake\Cors\HandleCors::class,
            ];

I tried to add the headers missed in index.php file on /public folder.

    //public/index.php
    use Illuminate\Contracts\Http\Kernel;
    use Illuminate\Http\Request;
    
    define('LARAVEL_START', microtime(true));
    header('Access-Control-Allow-Origin: *');
    header('Content-Type: application/json; charset = UTF-8');

   
Someone knows how to solve it? I can add more code if was necessary.

  [1]: https://github.com/gentritabazi01/Clean-Laravel-Api
  [2]: https://github.com/fruitcake/laravel-cors

**Comment by VetonMuhaxhiri** [comment]
Whats under `config/cors.php` file ?

**Comment by nerpianicolindo** [comment]
> Whats under `config/cors.php` file ?

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Laravel CORS Options
    |--------------------------------------------------------------------------
    |
    | The allowed_methods and allowed_headers options are case-insensitive.
    |
    | You don't need to provide both allowed_origins and allowed_origins_patterns.
    | If one of the strings passed matches, it is considered a valid origin.
    |
    | If ['*'] is provided to allowed_methods, allowed_origins or allowed_headers
    | all methods / origins / headers are allowed.
    |
    */

    /*
     * You can enable CORS for 1 or multiple paths.
     * Example: ['api/*']
     */
    'paths' => ['*'],

    /*
    * Matches the request method. `['*']` allows all methods.
    */
    'allowed_methods' => ['*'],

    /*
     * Matches the request origin. `['*']` allows all origins. Wildcards can be used, eg `*.mydomain.com`
     */
    'allowed_origins' => ['*'],

    /*
     * Patterns that can be used with `preg_match` to match the origin.
     */
    'allowed_origins_patterns' => [],

    /*
     * Sets the Access-Control-Allow-Headers response header. `['*']` allows all headers.
     */
    'allowed_headers' => ['*'],

    /*
     * Sets the Access-Control-Expose-Headers response header with these headers.
     */
    'exposed_headers' => [],

    /*
     * Sets the Access-Control-Max-Age response header when > 0.
     */
    'max_age' => 0,

    /*
     * Sets the Access-Control-Allow-Credentials header.
     */
    'supports_credentials' => false,
];

```

**Comment by VetonMuhaxhiri** [comment]
The file looks Ok? When did you get this error? Did it work properly before ?

**Comment by gentritabazi** [comment]
Here are some gotchas when using fruitcake/laravel-cors:

Put `HandleCors` middleware at the top of $middleware in `/infrastructure/Http/Kernel.php`:


```php
protected $middleware = [
    \Fruitcake\Cors\HandleCors::class,
    ...
];
```

Putting it at the bottom or somewhere between won't work because requests might be rejected by other middlewares with higher priority.

**Comment by nerpianicolindo** [comment]
> Here are some gotchas when using fruitcake/laravel-cors:
> 
> Put `HandleCors` middleware at the top of $middleware in `/infrastructure/Http/Kernel.php`:
> 
> ```
> protected $middleware = [
>     \Fruitcake\Cors\HandleCors::class,
>     ...
> ];
> ```
> 
> Putting it at the bottom or somewhere between won't work because requests might be rejected by other middlewares with higher priority.

I tried it before but didn't work.... This morning i woke up inspired and i find a solution.
I have removed everything related with cors in my project and i added this lines in /public/web.config
```
<httpProtocol>
    <customHeaders>
        <add name="Access-Control-Allow-Headers" value="*" />
        <add name="Access-Control-Allow-Origin" value="*" />
    </customHeaders>
</httpProtocol>
```
All this lines where included inside markup "system.webServer" and my project start to work again. 
Im so sorry if i have wasted your time. Probably this was a stupid problem by my side. Thanks a lot for your help.
U rock!!
